### PR TITLE
Fix delete

### LINKED ISSUE #60: Fix delete methods
Currently the delete methods are broken because of major refactors. We should make them work again and add tests ;)

### PR DESCRIPTION
**Pull request by arj03**
Fixes #60 by making delete and deleteFeed work again. This depends on https://github.com/ssb-ngi-pointer/jitdb/pull/74 and https://github.com/flumedb/async-flumelog/pull/13.

### CODE REVIEW

File: log.js [hunk 1]
```diff
@@ -36,8 +36,7 @@ module.exports = function (dir, config, private) {
   let originalGet = log.get
   log.get = function (seq, cb) {
     originalGet(seq, (err, res) => {
-      if (err && err.code === 'flumelog:deleted') cb()
```
Comment (arj03) [inline log.js:39]: This was removed because we already handle this in jitdb and the only other place this is used is in EBT index and actually if that happens then this means that you delete a message from an author but not the whole feed and this scenario shouldn't be supported in EBT anyway.

**Comment by arj03** [comment]
While writing this I noticed that we really need proper documentation of the different methods. I think after merging this in would be a good point to add that.

File: db.js [hunk 2]
```diff
@@ -114,49 +121,35 @@ exports.init = function (sbot, dir, config) {
...
-          )
-        }
+    jitdb.all(author(feedId), 0, false, true, (err, results) => {
+      push(
+        push.values(results),
+        push.asyncMap((seq, cb) => {
+          log.del(seq, cb)
+        }),
+        push.collect((err) => {
+          if (!err) {
```
Comment (staltz) [inline db.js:147]: This seems a bit backwards and made me stop and read it carefully. I think if it were written in a more standard way, would make it easy to skim:

```js
if (err) cb(err)
else {

}
```

File: db.js [hunk 3]
```diff
@@ -114,49 +121,35 @@ exports.init = function (sbot, dir, config) {
...
+  function del(msgId, cb) {
     const guard = guardAgainstDuplicateLogs('del()')
     if (guard) return cb(guard)
 
-    // FIXME: this doesn't work anymore after changing base index
-    baseIndex.keyToSeq(key, (err, seq) => {
+    jitdb.all(key(msgId), 0, false, true, (err, results) => {
       if (err) return cb(err)
-      if (seq == null) return cb(new Error('seq is null!'))
+      if (results.length === 0) return cb(new Error('seq is null!'))
```
Comment (staltz) [inline db.js:130]: The error message seems not relevant anymore, how about `'cannot delete ' + msgId + ' because it was not found'`

**Review by staltz — CHANGES_REQUESTED** [review]

File: test/delete.js [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+const db = sbot.db
+
+test('index, delete, query', (t) => {
+  const post = { type: 'post', text: 'Testing!' }
+  const post2 = { type: 'post', text: 'Testing 2!' }
+
+  db.publish(post, (err, postMsg) => {
+    t.error(err, 'no err')
+
+    db.log.onDrain(() => {
```
Comment (staltz) [inline test/delete.js:36]: Just a heads up that this might need to be rebased with #85 so that it's `db.getLog()` etc

**Comment by staltz** [comment]
What happened to the tests? They ran for 5h then were cancelled

**Comment by arj03** [comment]
Wierd, not sure. I plan on looking at this again and rebasing tonight or tomorrow.

**Comment by arj03** [comment]
Found the problem. It was a missing cb.

**Comment by arj03** [comment]
This should be ready now. @staltz do you want a release of master before getting this in?

**Comment by arj03** [comment]
Awww naawww, an error :(

**Comment by arj03** [comment]
I'm really fond of these automated tests, found a bug that didn't show up locally. The problem (in a test) is also in master.

**Comment by staltz** [comment]
> This should be ready now. @staltz do you want a release of master before getting this in?

Actually yeah, that would be useful. :)

This one can be merged IMO

**Comment by arj03** [comment]
Great, released current master as 0.8.0
